// Copyright 2015 The Vanadium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// This file was auto-generated by the vanadium vdl tool.
// Package: Chat

// Package Chat defines the Chat example interface.
//nolint:golint
package chat

import (
	v23 "v.io/v23"
	"v.io/v23/context"
	"v.io/v23/rpc"
)

var _ = initializeVDL() // Must be first; see initializeVDL comments for details.

// Interface definitions
// =====================

// ChatClientMethods is the client interface
// containing Chat methods.
//
// Chat is the interface to a Chat service.
type ChatClientMethods interface {
	// SendMessage sends a message to a user.
	SendMessage(_ *context.T, msg string, _ ...rpc.CallOpt) (string, error)
}

// ChatClientStub embeds ChatClientMethods and is a
// placeholder for additional management operations.
type ChatClientStub interface {
	ChatClientMethods
}

// ChatClient returns a client stub for Chat.
func ChatClient(name string) ChatClientStub {
	return implChatClientStub{name}
}

type implChatClientStub struct {
	name string
}

func (c implChatClientStub) SendMessage(ctx *context.T, i0 string, opts ...rpc.CallOpt) (o0 string, err error) {
	err = v23.GetClient(ctx).Call(ctx, c.name, "SendMessage", []interface{}{i0}, []interface{}{&o0}, opts...)
	return
}

// ChatServerMethods is the interface a server writer
// implements for Chat.
//
// Chat is the interface to a Chat-telling service.
type ChatServerMethods interface {
	// SendMessage sends a message to a user.
	SendMessage(_ *context.T, _ rpc.ServerCall, msg string) (string, error)
}

// ChatServerStubMethods is the server interface containing
// Chat methods, as expected by rpc.Server.
// There is no difference between this interface and ChatServerMethods
// since there are no streaming methods.
type ChatServerStubMethods ChatServerMethods

// ChatServerStub adds universal methods to ChatServerStubMethods.
type ChatServerStub interface {
	ChatServerStubMethods
	// DescribeInterfaces the Chat interfaces.
	Describe__() []rpc.InterfaceDesc
}

// ChatServer returns a server stub for Chat.
// It converts an implementation of ChatServerMethods into
// an object that may be used by rpc.Server.
func ChatServer(impl ChatServerMethods) ChatServerStub {
	stub := implChatServerStub{
		impl: impl,
	}
	// Initialize GlobState; always check the stub itself first, to handle the
	// case where the user has the Glob method defined in their VDL source.
	if gs := rpc.NewGlobState(stub); gs != nil {
		stub.gs = gs
	} else if gs := rpc.NewGlobState(impl); gs != nil {
		stub.gs = gs
	}
	return stub
}

type implChatServerStub struct {
	impl ChatServerMethods
	gs   *rpc.GlobState
}

func (s implChatServerStub) SendMessage(ctx *context.T, call rpc.ServerCall, i0 string) (string, error) {
	return s.impl.SendMessage(ctx, call, i0)
}

func (s implChatServerStub) Globber() *rpc.GlobState {
	return s.gs
}

func (s implChatServerStub) Describe__() []rpc.InterfaceDesc {
	return []rpc.InterfaceDesc{ChatDesc}
}

// ChatDesc describes the Chat interface.
var ChatDesc rpc.InterfaceDesc = descChat

// descChat hides the desc to keep godoc clean.
var descChat = rpc.InterfaceDesc{
	Name:    "Chat",
	PkgPath: "",
	Doc:     "// Chat is the interface to a p2p chat service.",
	Methods: []rpc.MethodDesc{
		{
			Name: "SendMessage",
			Doc:  "// Sends a message to a client.",
			InArgs: []rpc.ArgDesc{
				{Name: "Chat", Doc: ``}, // string
			},
		},
	},
}

var initializeVDLCalled bool

// initializeVDL performs vdl initialization.  It is safe to call multiple times.
// If you have an init ordering issue, just insert the following line verbatim
// into your source files in this package, right after the "package foo" clause:
//
//    var _ = initializeVDL()
//
// The purpose of this function is to ensure that vdl initialization occurs in
// the right order, and very early in the init sequence.  In particular, vdl
// registration and package variable initialization needs to occur before
// functions like vdl.TypeOf will work properly.
//
// This function returns a dummy value, so that it can be used to initialize the
// first var in the file, to take advantage of Go's defined init order.
func initializeVDL() struct{} {
	if initializeVDLCalled {
		return struct{}{}
	}
	initializeVDLCalled = true

	return struct{}{}
}
